<a href="https://colab.research.google.com/github/Alisha2799/EDA/blob/main/Job_Lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv("/content/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [2]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [3]:
model.predict([[5000]])


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [7]:
pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import joblib

In [10]:
joblib.dump(model,"model_joblib")

['model_joblib']

In [12]:
mj=joblib.load("model_joblib")

In [13]:
mj.coef_

array([135.78767123])

In [14]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])