<a href="https://colab.research.google.com/github/Alisha2799/EDA/blob/main/ML2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=680044dc1b5581faf20bcb65e249be74f4d29fb05d76c785849754f277e03dc3
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [4]:
pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from sklearn import linear_model

In [8]:
df=pd.read_csv(r"/content/homeprices2.csv")

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
df.bedrooms.median()

4.0

In [18]:
import math

In [22]:
b=math.floor(df.bedrooms.median())
b

4

In [25]:
df['bedrooms'] = df['bedrooms'].replace(np.nan, b) # df.bedrooms=df.bedrooms.fillna(b) using pandas

In [24]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [26]:
reg=linear_model.LinearRegression()

In [29]:
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [31]:
reg.coef_# m1 , m2 , m3

array([  112.06244194, 23388.88007794, -3231.71790863])

In [32]:
reg.intercept_

221323.00186540396

In [35]:
reg.predict([[3000,3,50]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([466091.07249398])

In [37]:
reg.predict([[5000,4,50]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([713604.83645619])